# Generated by Django 5.2.8 on 2026-04-21 05:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries_back_end', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='entry_vector',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
    ]
