# Generated by Django 5.2.8 on 2026-04-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries_back_end', '0002_entries_entry_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='is_embedded',
            field=models.BooleanField(default=False),
        ),
    ]
