# Generated by Django 5.2.8 on 2026-04-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries_back_end', '0003_entries_is_embedded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entries',
            name='is_embedded',
        ),
        migrations.AlterField(
            model_name='entries',
            name='entry_vector',
            field=models.BinaryField(),
        ),
    ]
