# Generated by Django 5.2.8 on 2026-05-02 13:03

from django.db import migrations
from pgvector.django import VectorExtension 

class Migration(migrations.Migration):

    dependencies = [
        ('entries_back_end', '0003_entries_is_embedded'),
    ]

    operations = [
        VectorExtension()
    ]
