# Generated by Django 5.2.8 on 2026-05-02 13:07

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries_back_end', '0005_pgvector_mig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='entry_vector',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
