# Generated by Django 5.2.8 on 2026-05-02 13:09

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries_back_end', '0006_alter_entries_entry_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entries',
            name='entry_vector',
        ),
        migrations.AddField(
            model_name='entries',
            name='entry_vectors',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
