# Generated by Django 5.2.8 on 2026-05-02 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries_back_end', '0007_remove_entries_entry_vector_entries_entry_vectors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entries',
            name='is_embedded',
        ),
    ]
