# Generated by Django 5.2.8 on 2025-11-17 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries_back_end', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entries',
            old_name='tiitle_test',
            new_name='tittle_text',
        ),
    ]
