# Generated by Django 5.2.8 on 2026-01-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries_back_end', '0002_rename_tiitle_test_entries_tittle_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entries',
            old_name='tittle_text',
            new_name='title_text',
        ),
        migrations.AlterField(
            model_name='entries',
            name='entry_text',
            field=models.TextField(),
        ),
    ]
