# Generated by Django 5.2.8 on 2026-01-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries_back_end', '0003_rename_tittle_text_entries_title_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='save_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
